export const constants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    POLLS_GETALL_REQUEST: 'POLLS_GETALL_REQUEST',
    POLLS_GETALL_SUCCESS: 'POLLS_GETALL_SUCCESS',
    POLLS_GETALL_FAILURE: 'POLLS_GETALL_FAILURE',

    POLL_CREATE_REQUEST: 'POLL_CREATE_REQUEST',
    POLL_CREATE_SUCCESS: 'POLL_CREATE_SUCCESS',
    POLL_CREATE_FAILURE: 'POLL_CREATE_FAILURE',

    POLL_CLOSE_REQUEST: 'POLL_CLOSE_REQUEST',
    POLL_CLOSE_SUCCESS: 'POLL_CLOSE_SUCCESS',
    POLL_CLOSE_FAILURE: 'POLL_CLOSE_FAILURE',

    POLL_VOTE_REQUEST: 'POLL_VOTE_REQUEST',
    POLL_VOTE_SUCCESS: 'POLL_VOTE_SUCCESS',
    POLL_VOTE_FAILURE: 'POLL_VOTE_FAILURE',

    TOGGLE_CREATE_POLL_MODAL: 'TOGGLE_CREATE_POLL_MODAL',
    CLEAR_ALL_POLLS: 'CLEAR_ALL_POLLS'

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};

export const apiUrl = 'http://www.localhost:4000';
